using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AppGloboXamarin.Resources.FontAwesome
{
    public static class FontAwesome
    {
        //			public static String getFAString2(String t)
        //		{
        //			//Puoi scrivere quando la chiami AppIncaricate.FontAwesome.getFSString("Glass"); -> in teoria
        //			return "FA" +  this.GetType ().GetRuntimeProperty (t).GetValue (t);
        //		}

        public static String getFAString(String str)
        {
            String res = "";

            switch (str)
            {
                case "Glass": { res = "\uf000"; break; }
                case "Music": { res = "\uf001"; break; }
                case "Search": { res = "\uf002"; break; }
                case "EnvelopeO": { res = "\uf003"; break; }
                case "Heart": { res = "\uf004"; break; }
                case "Star": { res = "\uf005"; break; }
                case "StarO": { res = "\uf006"; break; }
                case "User": { res = "\uf007"; break; }
                case "Film": { res = "\uf008"; break; }
                case "ThLarge": { res = "\uf009"; break; }
                case "Th": { res = "\uf00a"; break; }
                case "ThList": { res = "\uf00b"; break; }
                case "Check": { res = "\uf00c"; break; }
                case "Times": { res = "\uf00d"; break; }
                case "SearchPlus": { res = "\uf00e"; break; }
                case "SearchMinus": { res = "\uf010"; break; }
                case "PowerOff": { res = "\uf011"; break; }
                case "Signal": { res = "\uf012"; break; }
                case "Cog": { res = "\uf013"; break; }
                case "TrashO": { res = "\uf014"; break; }
                case "Home": { res = "\uf015"; break; }
                case "FileO": { res = "\uf016"; break; }
                case "ClockO": { res = "\uf017"; break; }
                case "Road": { res = "\uf018"; break; }
                case "Download": { res = "\uf019"; break; }
                case "ArrowCircleODown": { res = "\uf01a"; break; }
                case "ArrowCircleOUp": { res = "\uf01b"; break; }
                case "Inbox": { res = "\uf01c"; break; }
                case "PlayCircleO": { res = "\uf01d"; break; }
                case "Repeat": { res = "\uf01e"; break; }
                case "Refresh": { res = "\uf021"; break; }
                case "ListAlt": { res = "\uf022"; break; }
                case "Lock": { res = "\uf023"; break; }
                case "Flag": { res = "\uf024"; break; }
                case "Headphones": { res = "\uf025"; break; }
                case "VolumeOff": { res = "\uf026"; break; }
                case "VolumeDown": { res = "\uf027"; break; }
                case "VolumeUp": { res = "\uf028"; break; }
                case "Qrcode": { res = "\uf029"; break; }
                case "Barcode": { res = "\uf02a"; break; }
                case "Tag": { res = "\uf02b"; break; }
                case "Tags": { res = "\uf02c"; break; }
                case "Book": { res = "\uf02d"; break; }
                case "Bookmark": { res = "\uf02e"; break; }
                case "Print": { res = "\uf02f"; break; }
                case "Camera": { res = "\uf030"; break; }
                case "Font": { res = "\uf031"; break; }
                case "Bold": { res = "\uf032"; break; }
                case "Italic": { res = "\uf033"; break; }
                case "TextHeight": { res = "\uf034"; break; }
                case "TextWidth": { res = "\uf035"; break; }
                case "AlignLeft": { res = "\uf036"; break; }
                case "AlignCenter": { res = "\uf037"; break; }
                case "AlignRight": { res = "\uf038"; break; }
                case "AlignJustify": { res = "\uf039"; break; }
                case "List": { res = "\uf03a"; break; }
                case "Outdent": { res = "\uf03b"; break; }
                case "Indent": { res = "\uf03c"; break; }
                case "VideoCamera": { res = "\uf03d"; break; }
                case "PictureO": { res = "\uf03e"; break; }
                case "Pencil": { res = "\uf040"; break; }
                case "MapMarker": { res = "\uf041"; break; }
                case "Adjust": { res = "\uf042"; break; }
                case "Tint": { res = "\uf043"; break; }
                case "PencilSquareO": { res = "\uf044"; break; }
                case "ShareSquareO": { res = "\uf045"; break; }
                case "CheckSquareO": { res = "\uf046"; break; }
                case "Arrows": { res = "\uf047"; break; }
                case "StepBackward": { res = "\uf048"; break; }
                case "FastBackward": { res = "\uf049"; break; }
                case "Backward": { res = "\uf04a"; break; }
                case "Play": { res = "\uf04b"; break; }
                case "Pause": { res = "\uf04c"; break; }
                case "Stop": { res = "\uf04d"; break; }
                case "Forward": { res = "\uf04e"; break; }
                case "FastForward": { res = "\uf050"; break; }
                case "StepForward": { res = "\uf051"; break; }
                case "Eject": { res = "\uf052"; break; }
                case "ChevronLeft": { res = "\uf053"; break; }
                case "ChevronRight": { res = "\uf054"; break; }
                case "PlusCircle": { res = "\uf055"; break; }
                case "MinusCircle": { res = "\uf056"; break; }
                case "TimesCircle": { res = "\uf057"; break; }
                case "CheckCircle": { res = "\uf058"; break; }
                case "QuestionCircle": { res = "\uf059"; break; }
                case "InfoCircle": { res = "\uf05a"; break; }
                case "Crosshairs": { res = "\uf05b"; break; }
                case "TimesCircleO": { res = "\uf05c"; break; }
                case "CheckCircleO": { res = "\uf05d"; break; }
                case "Ban": { res = "\uf05e"; break; }
                case "ArrowLeft": { res = "\uf060"; break; }
                case "ArrowRight": { res = "\uf061"; break; }
                case "ArrowUp": { res = "\uf062"; break; }
                case "ArrowDown": { res = "\uf063"; break; }
                case "Share": { res = "\uf064"; break; }
                case "Expand": { res = "\uf065"; break; }
                case "Compress": { res = "\uf066"; break; }
                case "Plus": { res = "\uf067"; break; }
                case "Minus": { res = "\uf068"; break; }
                case "Asterisk": { res = "\uf069"; break; }
                case "ExclamationCircle": { res = "\uf06a"; break; }
                case "Gift": { res = "\uf06b"; break; }
                case "Leaf": { res = "\uf06c"; break; }
                case "Fire": { res = "\uf06d"; break; }
                case "Eye": { res = "\uf06e"; break; }
                case "EyeSlash": { res = "\uf070"; break; }
                case "ExclamationTriangle": { res = "\uf071"; break; }
                case "Plane": { res = "\uf072"; break; }
                case "Calendar": { res = "\uf073"; break; }
                case "Random": { res = "\uf074"; break; }
                case "Comment": { res = "\uf075"; break; }
                case "Magnet": { res = "\uf076"; break; }
                case "ChevronUp": { res = "\uf077"; break; }
                case "ChevronDown": { res = "\uf078"; break; }
                case "Retweet": { res = "\uf079"; break; }
                case "ShoppingCart": { res = "\uf07a"; break; }
                case "Folder": { res = "\uf07b"; break; }
                case "FolderOpen": { res = "\uf07c"; break; }
                case "ArrowsV": { res = "\uf07d"; break; }
                case "ArrowsH": { res = "\uf07e"; break; }
                case "BarChartO": { res = "\uf080"; break; }
                case "TwitterSquare": { res = "\uf081"; break; }
                case "FacebookSquare": { res = "\uf082"; break; }
                case "CameraRetro": { res = "\uf083"; break; }
                case "Key": { res = "\uf084"; break; }
                case "Cogs": { res = "\uf085"; break; }
                case "Comments": { res = "\uf086"; break; }
                case "ThumbsOUp": { res = "\uf087"; break; }
                case "ThumbsODown": { res = "\uf088"; break; }
                case "StarHalf": { res = "\uf089"; break; }
                case "HeartO": { res = "\uf08a"; break; }
                case "SignOut": { res = "\uf08b"; break; }
                case "LinkedinSquare": { res = "\uf08c"; break; }
                case "ThumbTack": { res = "\uf08d"; break; }
                case "ExternalLink": { res = "\uf08e"; break; }
                case "SignIn": { res = "\uf090"; break; }
                case "Trophy": { res = "\uf091"; break; }
                case "GithubSquare": { res = "\uf092"; break; }
                case "Upload": { res = "\uf093"; break; }
                case "LemonO": { res = "\uf094"; break; }
                case "Phone": { res = "\uf095"; break; }
                case "SquareO": { res = "\uf096"; break; }
                case "BookmarkO": { res = "\uf097"; break; }
                case "PhoneSquare": { res = "\uf098"; break; }
                case "Twitter": { res = "\uf099"; break; }
                case "Facebook": { res = "\uf09a"; break; }
                case "Github": { res = "\uf09b"; break; }
                case "Unlock": { res = "\uf09c"; break; }
                case "CreditCard": { res = "\uf09d"; break; }
                case "Rss": { res = "\uf09e"; break; }
                case "HddO": { res = "\uf0a0"; break; }
                case "Bullhorn": { res = "\uf0a1"; break; }
                case "Bell": { res = "\uf0f3"; break; }
                case "Certificate": { res = "\uf0a3"; break; }
                case "HandORight": { res = "\uf0a4"; break; }
                case "HandOLeft": { res = "\uf0a5"; break; }
                case "HandOUp": { res = "\uf0a6"; break; }
                case "HandODown": { res = "\uf0a7"; break; }
                case "ArrowCircleLeft": { res = "\uf0a8"; break; }
                case "ArrowCircleRight": { res = "\uf0a9"; break; }
                case "ArrowCircleUp": { res = "\uf0aa"; break; }
                case "ArrowCircleDown": { res = "\uf0ab"; break; }
                case "Globe": { res = "\uf0ac"; break; }
                case "Wrench": { res = "\uf0ad"; break; }
                case "Tasks": { res = "\uf0ae"; break; }
                case "Filter": { res = "\uf0b0"; break; }
                case "Briefcase": { res = "\uf0b1"; break; }
                case "ArrowsAlt": { res = "\uf0b2"; break; }
                case "Users": { res = "\uf0c0"; break; }
                case "Link": { res = "\uf0c1"; break; }
                case "Cloud": { res = "\uf0c2"; break; }
                case "Flask": { res = "\uf0c3"; break; }
                case "Scissors": { res = "\uf0c4"; break; }
                case "FilesO": { res = "\uf0c5"; break; }
                case "Paperclip": { res = "\uf0c6"; break; }
                case "FloppyO": { res = "\uf0c7"; break; }
                case "Square": { res = "\uf0c8"; break; }
                case "Bars": { res = "\uf0c9"; break; }
                case "ListUl": { res = "\uf0ca"; break; }
                case "ListOl": { res = "\uf0cb"; break; }
                case "Strikethrough": { res = "\uf0cc"; break; }
                case "Underline": { res = "\uf0cd"; break; }
                case "Table": { res = "\uf0ce"; break; }
                case "Magic": { res = "\uf0d0"; break; }
                case "Truck": { res = "\uf0d1"; break; }
                case "Pinterest": { res = "\uf0d2"; break; }
                case "PinterestSquare": { res = "\uf0d3"; break; }
                case "GooglePlusSquare": { res = "\uf0d4"; break; }
                case "GooglePlus": { res = "\uf0d5"; break; }
                case "Money": { res = "\uf0d6"; break; }
                case "CaretDown": { res = "\uf0d7"; break; }
                case "CaretUp": { res = "\uf0d8"; break; }
                case "CaretLeft": { res = "\uf0d9"; break; }
                case "CaretRight": { res = "\uf0da"; break; }
                case "Columns": { res = "\uf0db"; break; }
                case "Sort": { res = "\uf0dc"; break; }
                case "SortAsc": { res = "\uf0dd"; break; }
                case "SortDesc": { res = "\uf0de"; break; }
                case "Envelope": { res = "\uf0e0"; break; }
                case "Linkedin": { res = "\uf0e1"; break; }
                case "Undo": { res = "\uf0e2"; break; }
                case "Gavel": { res = "\uf0e3"; break; }
                case "Tachometer": { res = "\uf0e4"; break; }
                case "CommentO": { res = "\uf0e5"; break; }
                case "CommentsO": { res = "\uf0e6"; break; }
                case "Bolt": { res = "\uf0e7"; break; }
                case "Sitemap": { res = "\uf0e8"; break; }
                case "Umbrella": { res = "\uf0e9"; break; }
                case "Clipboard": { res = "\uf0ea"; break; }
                case "LightbulbO": { res = "\uf0eb"; break; }
                case "Exchange": { res = "\uf0ec"; break; }
                case "CloudDownload": { res = "\uf0ed"; break; }
                case "CloudUpload": { res = "\uf0ee"; break; }
                case "UserMd": { res = "\uf0f0"; break; }
                case "Stethoscope": { res = "\uf0f1"; break; }
                case "Suitcase": { res = "\uf0f2"; break; }
                case "BellO": { res = "\uf0a2"; break; }
                case "Coffee": { res = "\uf0f4"; break; }
                case "Cutlery": { res = "\uf0f5"; break; }
                case "FileTextO": { res = "\uf0f6"; break; }
                case "BuildingO": { res = "\uf0f7"; break; }
                case "HospitalO": { res = "\uf0f8"; break; }
                case "Ambulance": { res = "\uf0f9"; break; }
                case "Medkit": { res = "\uf0fa"; break; }
                case "FighterJet": { res = "\uf0fb"; break; }
                case "Beer": { res = "\uf0fc"; break; }
                case "HSquare": { res = "\uf0fd"; break; }
                case "PlusSquare": { res = "\uf0fe"; break; }
                case "AngleDoubleLeft": { res = "\uf100"; break; }
                case "AngleDoubleRight": { res = "\uf101"; break; }
                case "AngleDoubleUp": { res = "\uf102"; break; }
                case "AngleDoubleDown": { res = "\uf103"; break; }
                case "AngleLeft": { res = "\uf104"; break; }
                case "AngleRight": { res = "\uf105"; break; }
                case "AngleUp": { res = "\uf106"; break; }
                case "AngleDown": { res = "\uf107"; break; }
                case "Desktop": { res = "\uf108"; break; }
                case "Laptop": { res = "\uf109"; break; }
                case "Tablet": { res = "\uf10a"; break; }
                case "Mobile": { res = "\uf10b"; break; }
                case "CircleO": { res = "\uf10c"; break; }
                case "QuoteLeft": { res = "\uf10d"; break; }
                case "QuoteRight": { res = "\uf10e"; break; }
                case "Spinner": { res = "\uf110"; break; }
                case "Circle": { res = "\uf111"; break; }
                case "Reply": { res = "\uf112"; break; }
                case "GithubAlt": { res = "\uf113"; break; }
                case "FolderO": { res = "\uf114"; break; }
                case "FolderOpenO": { res = "\uf115"; break; }
                case "SmileO": { res = "\uf118"; break; }
                case "FrownO": { res = "\uf119"; break; }
                case "MehO": { res = "\uf11a"; break; }
                case "Gamepad": { res = "\uf11b"; break; }
                case "KeyboardO": { res = "\uf11c"; break; }
                case "FlagO": { res = "\uf11d"; break; }
                case "FlagCheckered": { res = "\uf11e"; break; }
                case "Terminal": { res = "\uf120"; break; }
                case "Code": { res = "\uf121"; break; }
                case "ReplyAll": { res = "\uf122"; break; }
                case "MailReplyAll": { res = "\uf122"; break; }
                case "StarHalfO": { res = "\uf123"; break; }
                case "LocationArrow": { res = "\uf124"; break; }
                case "Crop": { res = "\uf125"; break; }
                case "CodeFork": { res = "\uf126"; break; }
                case "ChainBroken": { res = "\uf127"; break; }
                case "Question": { res = "\uf128"; break; }
                case "Info": { res = "\uf129"; break; }
                case "Exclamation": { res = "\uf12a"; break; }
                case "Superscript": { res = "\uf12b"; break; }
                case "Subscript": { res = "\uf12c"; break; }
                case "Eraser": { res = "\uf12d"; break; }
                case "PuzzlePiece": { res = "\uf12e"; break; }
                case "Microphone": { res = "\uf130"; break; }
                case "MicrophoneSlash": { res = "\uf131"; break; }
                case "Shield": { res = "\uf132"; break; }
                case "CalendarO": { res = "\uf133"; break; }
                case "FireExtinguisher": { res = "\uf134"; break; }
                case "Rocket": { res = "\uf135"; break; }
                case "Maxcdn": { res = "\uf136"; break; }
                case "ChevronCircleLeft": { res = "\uf137"; break; }
                case "ChevronCircleRight": { res = "\uf138"; break; }
                case "ChevronCircleUp": { res = "\uf139"; break; }
                case "ChevronCircleDown": { res = "\uf13a"; break; }
                case "Html5": { res = "\uf13b"; break; }
                case "Css3": { res = "\uf13c"; break; }
                case "Anchor": { res = "\uf13d"; break; }
                case "UnlockAlt": { res = "\uf13e"; break; }
                case "Bullseye": { res = "\uf140"; break; }
                case "EllipsisH": { res = "\uf141"; break; }
                case "EllipsisV": { res = "\uf142"; break; }
                case "RssSquare": { res = "\uf143"; break; }
                case "PlayCircle": { res = "\uf144"; break; }
                case "Ticket": { res = "\uf145"; break; }
                case "MinusSquare": { res = "\uf146"; break; }
                case "MinusSquareO": { res = "\uf147"; break; }
                case "LevelUp": { res = "\uf148"; break; }
                case "LevelDown": { res = "\uf149"; break; }
                case "CheckSquare": { res = "\uf14a"; break; }
                case "PencilSquare": { res = "\uf14b"; break; }
                case "ExternalLinkSquare": { res = "\uf14c"; break; }
                case "ShareSquare": { res = "\uf14d"; break; }
                case "Compass": { res = "\uf14e"; break; }
                case "CaretSquareODown": { res = "\uf150"; break; }
                case "CaretSquareOUp": { res = "\uf151"; break; }
                case "CaretSquareORight": { res = "\uf152"; break; }
                case "Eur": { res = "\uf153"; break; }
                case "Gbp": { res = "\uf154"; break; }
                case "Usd": { res = "\uf155"; break; }
                case "Inr": { res = "\uf156"; break; }
                case "Jpy": { res = "\uf157"; break; }
                case "Rub": { res = "\uf158"; break; }
                case "Krw": { res = "\uf159"; break; }
                case "Btc": { res = "\uf15a"; break; }
                case "File": { res = "\uf15b"; break; }
                case "FileText": { res = "\uf15c"; break; }
                case "SortAlphaAsc": { res = "\uf15d"; break; }
                case "SortAlphaDesc": { res = "\uf15e"; break; }
                case "SortAmountAsc": { res = "\uf160"; break; }
                case "SortAmountDesc": { res = "\uf161"; break; }
                case "SortNumericAsc": { res = "\uf162"; break; }
                case "SortNumericDesc": { res = "\uf163"; break; }
                case "ThumbsUp": { res = "\uf164"; break; }
                case "ThumbsDown": { res = "\uf165"; break; }
                case "YoutubeSquare": { res = "\uf166"; break; }
                case "Youtube": { res = "\uf167"; break; }
                case "Xing": { res = "\uf168"; break; }
                case "XingSquare": { res = "\uf169"; break; }
                case "YoutubePlay": { res = "\uf16a"; break; }
                case "Dropbox": { res = "\uf16b"; break; }
                case "StackOverflow": { res = "\uf16c"; break; }
                case "Instagram": { res = "\uf16d"; break; }
                case "Flickr": { res = "\uf16e"; break; }
                case "Adn": { res = "\uf170"; break; }
                case "Bitbucket": { res = "\uf171"; break; }
                case "BitbucketSquare": { res = "\uf172"; break; }
                case "Tumblr": { res = "\uf173"; break; }
                case "TumblrSquare": { res = "\uf174"; break; }
                case "LongArrowDown": { res = "\uf175"; break; }
                case "LongArrowUp": { res = "\uf176"; break; }
                case "LongArrowLeft": { res = "\uf177"; break; }
                case "LongArrowRight": { res = "\uf178"; break; }
                case "Apple": { res = "\uf179"; break; }
                case "Windows": { res = "\uf17a"; break; }
                case "Android": { res = "\uf17b"; break; }
                case "Linux": { res = "\uf17c"; break; }
                case "Dribbble": { res = "\uf17d"; break; }
                case "Skype": { res = "\uf17e"; break; }
                case "Foursquare": { res = "\uf180"; break; }
                case "Trello": { res = "\uf181"; break; }
                case "Female": { res = "\uf182"; break; }
                case "Male": { res = "\uf183"; break; }
                case "Gittip": { res = "\uf184"; break; }
                case "SunO": { res = "\uf185"; break; }
                case "MoonO": { res = "\uf186"; break; }
                case "Archive": { res = "\uf187"; break; }
                case "Bug": { res = "\uf188"; break; }
                case "Vk": { res = "\uf189"; break; }
                case "Weibo": { res = "\uf18a"; break; }
                case "Renren": { res = "\uf18b"; break; }
                case "Pagelines": { res = "\uf18c"; break; }
                case "StackExchange": { res = "\uf18d"; break; }
                case "ArrowCircleORight": { res = "\uf18e"; break; }
                case "ArrowCircleOLeft": { res = "\uf190"; break; }
                case "CaretSquareOLeft": { res = "\uf191"; break; }
                case "DotCircleO": { res = "\uf192"; break; }
                case "Wheelchair": { res = "\uf193"; break; }
                case "VimeoSquare": { res = "\uf194"; break; }
                case "Try": { res = "\uf195"; break; }
                case "PlusSquareO": { res = "\uf196"; break; }
            }

            return res;
        }

        public static string FAGlass = "\uf000";
        public static string FAMusic = "\uf001";
        public static string FASearch = "\uf002";
        public static string FAEnvelopeO = "\uf003";
        public static string FAHeart = "\uf004";
        public static string FAStar = "\uf005";
        public static string FAStarO = "\uf006";
        public static string FAUser = "\uf007";
        public static string FAFilm = "\uf008";
        public static string FAThLarge = "\uf009";
        public static string FATh = "\uf00a";
        public static string FAThList = "\uf00b";
        public static string FACheck = "\uf00c";
        public static string FATimes = "\uf00d";
        public static string FASearchPlus = "\uf00e";
        public static string FASearchMinus = "\uf010";
        public static string FAPowerOff = "\uf011";
        public static string FASignal = "\uf012";
        public static string FACog = "\uf013";
        public static string FATrashO = "\uf014";
        public static string FAHome = "\uf015";
        public static string FAFileO = "\uf016";
        public static string FAClockO = "\uf017";
        public static string FARoad = "\uf018";
        public static string FADownload = "\uf019";
        public static string FAArrowCircleODown = "\uf01a";
        public static string FAArrowCircleOUp = "\uf01b";
        public static string FAInbox = "\uf01c";
        public static string FAPlayCircleO = "\uf01d";
        public static string FARepeat = "\uf01e";
        public static string FARefresh = "\uf021";
        public static string FAListAlt = "\uf022";
        public static string FALock = "\uf023";
        public static string FAFlag = "\uf024";
        public static string FAHeadphones = "\uf025";
        public static string FAVolumeOff = "\uf026";
        public static string FAVolumeDown = "\uf027";
        public static string FAVolumeUp = "\uf028";
        public static string FAQrcode = "\uf029";
        public static string FABarcode = "\uf02a";
        public static string FATag = "\uf02b";
        public static string FATags = "\uf02c";
        public static string FABook = "\uf02d";
        public static string FABookmark = "\uf02e";
        public static string FAPrint = "\uf02f";
        public static string FACamera = "\uf030";
        public static string FAFont = "\uf031";
        public static string FABold = "\uf032";
        public static string FAItalic = "\uf033";
        public static string FATextHeight = "\uf034";
        public static string FATextWidth = "\uf035";
        public static string FAAlignLeft = "\uf036";
        public static string FAAlignCenter = "\uf037";
        public static string FAAlignRight = "\uf038";
        public static string FAAlignJustify = "\uf039";
        public static string FAList = "\uf03a";
        public static string FAOutdent = "\uf03b";
        public static string FAIndent = "\uf03c";
        public static string FAVideoCamera = "\uf03d";
        public static string FAPictureO = "\uf03e";
        public static string FAPencil = "\uf040";
        public static string FAMapMarker = "\uf041";
        public static string FAAdjust = "\uf042";
        public static string FATint = "\uf043";
        public static string FAPencilSquareO = "\uf044";
        public static string FAShareSquareO = "\uf045";
        public static string FACheckSquareO = "\uf046";
        public static string FAArrows = "\uf047";
        public static string FAStepBackward = "\uf048";
        public static string FAFastBackward = "\uf049";
        public static string FABackward = "\uf04a";
        public static string FAPlay = "\uf04b";
        public static string FAPause = "\uf04c";
        public static string FAStop = "\uf04d";
        public static string FAForward = "\uf04e";
        public static string FAFastForward = "\uf050";
        public static string FAStepForward = "\uf051";
        public static string FAEject = "\uf052";
        public static string FAChevronLeft = "\uf053";
        public static string FAChevronRight = "\uf054";
        public static string FAPlusCircle = "\uf055";
        public static string FAMinusCircle = "\uf056";
        public static string FATimesCircle = "\uf057";
        public static string FACheckCircle = "\uf058";
        public static string FAQuestionCircle = "\uf059";
        public static string FAInfoCircle = "\uf05a";
        public static string FACrosshairs = "\uf05b";
        public static string FATimesCircleO = "\uf05c";
        public static string FACheckCircleO = "\uf05d";
        public static string FABan = "\uf05e";
        public static string FAArrowLeft = "\uf060";
        public static string FAArrowRight = "\uf061";
        public static string FAArrowUp = "\uf062";
        public static string FAArrowDown = "\uf063";
        public static string FAShare = "\uf064";
        public static string FAExpand = "\uf065";
        public static string FACompress = "\uf066";
        public static string FAPlus = "\uf067";
        public static string FAMinus = "\uf068";
        public static string FAAsterisk = "\uf069";
        public static string FAExclamationCircle = "\uf06a";
        public static string FAGift = "\uf06b";
        public static string FALeaf = "\uf06c";
        public static string FAFire = "\uf06d";
        public static string FAEye = "\uf06e";
        public static string FAEyeSlash = "\uf070";
        public static string FAExclamationTriangle = "\uf071";
        public static string FAPlane = "\uf072";
        public static string FACalendar = "\uf073";
        public static string FARandom = "\uf074";
        public static string FAComment = "\uf075";
        public static string FAMagnet = "\uf076";
        public static string FAChevronUp = "\uf077";
        public static string FAChevronDown = "\uf078";
        public static string FARetweet = "\uf079";
        public static string FAShoppingCart = "\uf07a";
        public static string FAFolder = "\uf07b";
        public static string FAFolderOpen = "\uf07c";
        public static string FAArrowsV = "\uf07d";
        public static string FAArrowsH = "\uf07e";
        public static string FABarChartO = "\uf080";
        public static string FATwitterSquare = "\uf081";
        public static string FAFacebookSquare = "\uf082";
        public static string FACameraRetro = "\uf083";
        public static string FAKey = "\uf084";
        public static string FACogs = "\uf085";
        public static string FAComments = "\uf086";
        public static string FAThumbsOUp = "\uf087";
        public static string FAThumbsODown = "\uf088";
        public static string FAStarHalf = "\uf089";
        public static string FAHeartO = "\uf08a";
        public static string FASignOut = "\uf08b";
        public static string FALinkedinSquare = "\uf08c";
        public static string FAThumbTack = "\uf08d";
        public static string FAExternalLink = "\uf08e";
        public static string FASignIn = "\uf090";
        public static string FATrophy = "\uf091";
        public static string FAGithubSquare = "\uf092";
        public static string FAUpload = "\uf093";
        public static string FALemonO = "\uf094";
        public static string FAPhone = "\uf095";
        public static string FASquareO = "\uf096";
        public static string FABookmarkO = "\uf097";
        public static string FAPhoneSquare = "\uf098";
        public static string FATwitter = "\uf099";
        public static string FAFacebook = "\uf09a";
        public static string FAGithub = "\uf09b";
        public static string FAUnlock = "\uf09c";
        public static string FACreditCard = "\uf09d";
        public static string FARss = "\uf09e";
        public static string FAHddO = "\uf0a0";
        public static string FABullhorn = "\uf0a1";
        public static string FABell = "\uf0f3";
        public static string FACertificate = "\uf0a3";
        public static string FAHandORight = "\uf0a4";
        public static string FAHandOLeft = "\uf0a5";
        public static string FAHandOUp = "\uf0a6";
        public static string FAHandODown = "\uf0a7";
        public static string FAArrowCircleLeft = "\uf0a8";
        public static string FAArrowCircleRight = "\uf0a9";
        public static string FAArrowCircleUp = "\uf0aa";
        public static string FAArrowCircleDown = "\uf0ab";
        public static string FAGlobe = "\uf0ac";
        public static string FAWrench = "\uf0ad";
        public static string FATasks = "\uf0ae";
        public static string FAFilter = "\uf0b0";
        public static string FABriefcase = "\uf0b1";
        public static string FAArrowsAlt = "\uf0b2";
        public static string FAUsers = "\uf0c0";
        public static string FALink = "\uf0c1";
        public static string FACloud = "\uf0c2";
        public static string FAFlask = "\uf0c3";
        public static string FAScissors = "\uf0c4";
        public static string FAFilesO = "\uf0c5";
        public static string FAPaperclip = "\uf0c6";
        public static string FAFloppyO = "\uf0c7";
        public static string FASquare = "\uf0c8";
        public static string FABars = "\uf0c9";
        public static string FAListUl = "\uf0ca";
        public static string FAListOl = "\uf0cb";
        public static string FAStrikethrough = "\uf0cc";
        public static string FAUnderline = "\uf0cd";
        public static string FATable = "\uf0ce";
        public static string FAMagic = "\uf0d0";
        public static string FATruck = "\uf0d1";
        public static string FAPinterest = "\uf0d2";
        public static string FAPinterestSquare = "\uf0d3";
        public static string FAGooglePlusSquare = "\uf0d4";
        public static string FAGooglePlus = "\uf0d5";
        public static string FAMoney = "\uf0d6";
        public static string FACaretDown = "\uf0d7";
        public static string FACaretUp = "\uf0d8";
        public static string FACaretLeft = "\uf0d9";
        public static string FACaretRight = "\uf0da";
        public static string FAColumns = "\uf0db";
        public static string FASort = "\uf0dc";
        public static string FASortAsc = "\uf0dd";
        public static string FASortDesc = "\uf0de";
        public static string FAEnvelope = "\uf0e0";
        public static string FALinkedin = "\uf0e1";
        public static string FAUndo = "\uf0e2";
        public static string FAGavel = "\uf0e3";
        public static string FATachometer = "\uf0e4";
        public static string FACommentO = "\uf0e5";
        public static string FACommentsO = "\uf0e6";
        public static string FABolt = "\uf0e7";
        public static string FASitemap = "\uf0e8";
        public static string FAUmbrella = "\uf0e9";
        public static string FAClipboard = "\uf0ea";
        public static string FALightbulbO = "\uf0eb";
        public static string FAExchange = "\uf0ec";
        public static string FACloudDownload = "\uf0ed";
        public static string FACloudUpload = "\uf0ee";
        public static string FAUserMd = "\uf0f0";
        public static string FAStethoscope = "\uf0f1";
        public static string FASuitcase = "\uf0f2";
        public static string FABellO = "\uf0a2";
        public static string FACoffee = "\uf0f4";
        public static string FACutlery = "\uf0f5";
        public static string FAFileTextO = "\uf0f6";
        public static string FABuildingO = "\uf0f7";
        public static string FAHospitalO = "\uf0f8";
        public static string FAAmbulance = "\uf0f9";
        public static string FAMedkit = "\uf0fa";
        public static string FAFighterJet = "\uf0fb";
        public static string FABeer = "\uf0fc";
        public static string FAHSquare = "\uf0fd";
        public static string FAPlusSquare = "\uf0fe";
        public static string FAAngleDoubleLeft = "\uf100";
        public static string FAAngleDoubleRight = "\uf101";
        public static string FAAngleDoubleUp = "\uf102";
        public static string FAAngleDoubleDown = "\uf103";
        public static string FAAngleLeft = "\uf104";
        public static string FAAngleRight = "\uf105";
        public static string FAAngleUp = "\uf106";
        public static string FAAngleDown = "\uf107";
        public static string FADesktop = "\uf108";
        public static string FALaptop = "\uf109";
        public static string FATablet = "\uf10a";
        public static string FAMobile = "\uf10b";
        public static string FACircleO = "\uf10c";
        public static string FAQuoteLeft = "\uf10d";
        public static string FAQuoteRight = "\uf10e";
        public static string FASpinner = "\uf110";
        public static string FACircle = "\uf111";
        public static string FAReply = "\uf112";
        public static string FAGithubAlt = "\uf113";
        public static string FAFolderO = "\uf114";
        public static string FAFolderOpenO = "\uf115";
        public static string FASmileO = "\uf118";
        public static string FAFrownO = "\uf119";
        public static string FAMehO = "\uf11a";
        public static string FAGamepad = "\uf11b";
        public static string FAKeyboardO = "\uf11c";
        public static string FAFlagO = "\uf11d";
        public static string FAFlagCheckered = "\uf11e";
        public static string FATerminal = "\uf120";
        public static string FACode = "\uf121";
        public static string FAReplyAll = "\uf122";
        public static string FAMailReplyAll = "\uf122";
        public static string FAStarHalfO = "\uf123";
        public static string FALocationArrow = "\uf124";
        public static string FACrop = "\uf125";
        public static string FACodeFork = "\uf126";
        public static string FAChainBroken = "\uf127";
        public static string FAQuestion = "\uf128";
        public static string FAInfo = "\uf129";
        public static string FAExclamation = "\uf12a";
        public static string FASuperscript = "\uf12b";
        public static string FASubscript = "\uf12c";
        public static string FAEraser = "\uf12d";
        public static string FAPuzzlePiece = "\uf12e";
        public static string FAMicrophone = "\uf130";
        public static string FAMicrophoneSlash = "\uf131";
        public static string FAShield = "\uf132";
        public static string FACalendarO = "\uf133";
        public static string FAFireExtinguisher = "\uf134";
        public static string FARocket = "\uf135";
        public static string FAMaxcdn = "\uf136";
        public static string FAChevronCircleLeft = "\uf137";
        public static string FAChevronCircleRight = "\uf138";
        public static string FAChevronCircleUp = "\uf139";
        public static string FAChevronCircleDown = "\uf13a";
        public static string FAHtml5 = "\uf13b";
        public static string FACss3 = "\uf13c";
        public static string FAAnchor = "\uf13d";
        public static string FAUnlockAlt = "\uf13e";
        public static string FABullseye = "\uf140";
        public static string FAEllipsisH = "\uf141";
        public static string FAEllipsisV = "\uf142";
        public static string FARssSquare = "\uf143";
        public static string FAPlayCircle = "\uf144";
        public static string FATicket = "\uf145";
        public static string FAMinusSquare = "\uf146";
        public static string FAMinusSquareO = "\uf147";
        public static string FALevelUp = "\uf148";
        public static string FALevelDown = "\uf149";
        public static string FACheckSquare = "\uf14a";
        public static string FAPencilSquare = "\uf14b";
        public static string FAExternalLinkSquare = "\uf14c";
        public static string FAShareSquare = "\uf14d";
        public static string FACompass = "\uf14e";
        public static string FACaretSquareODown = "\uf150";
        public static string FACaretSquareOUp = "\uf151";
        public static string FACaretSquareORight = "\uf152";
        public static string FAEur = "\uf153";
        public static string FAGbp = "\uf154";
        public static string FAUsd = "\uf155";
        public static string FAInr = "\uf156";
        public static string FAJpy = "\uf157";
        public static string FARub = "\uf158";
        public static string FAKrw = "\uf159";
        public static string FABtc = "\uf15a";
        public static string FAFile = "\uf15b";
        public static string FAFileText = "\uf15c";
        public static string FASortAlphaAsc = "\uf15d";
        public static string FASortAlphaDesc = "\uf15e";
        public static string FASortAmountAsc = "\uf160";
        public static string FASortAmountDesc = "\uf161";
        public static string FASortNumericAsc = "\uf162";
        public static string FASortNumericDesc = "\uf163";
        public static string FAThumbsUp = "\uf164";
        public static string FAThumbsDown = "\uf165";
        public static string FAYoutubeSquare = "\uf166";
        public static string FAYoutube = "\uf167";
        public static string FAXing = "\uf168";
        public static string FAXingSquare = "\uf169";
        public static string FAYoutubePlay = "\uf16a";
        public static string FADropbox = "\uf16b";
        public static string FAStackOverflow = "\uf16c";
        public static string FAInstagram = "\uf16d";
        public static string FAFlickr = "\uf16e";
        public static string FAAdn = "\uf170";
        public static string FABitbucket = "\uf171";
        public static string FABitbucketSquare = "\uf172";
        public static string FATumblr = "\uf173";
        public static string FATumblrSquare = "\uf174";
        public static string FALongArrowDown = "\uf175";
        public static string FALongArrowUp = "\uf176";
        public static string FALongArrowLeft = "\uf177";
        public static string FALongArrowRight = "\uf178";
        public static string FAApple = "\uf179";
        public static string FAWindows = "\uf17a";
        public static string FAAndroid = "\uf17b";
        public static string FALinux = "\uf17c";
        public static string FADribbble = "\uf17d";
        public static string FASkype = "\uf17e";
        public static string FAFoursquare = "\uf180";
        public static string FATrello = "\uf181";
        public static string FAFemale = "\uf182";
        public static string FAMale = "\uf183";
        public static string FAGittip = "\uf184";
        public static string FASunO = "\uf185";
        public static string FAMoonO = "\uf186";
        public static string FAArchive = "\uf187";
        public static string FABug = "\uf188";
        public static string FAVk = "\uf189";
        public static string FAWeibo = "\uf18a";
        public static string FARenren = "\uf18b";
        public static string FAPagelines = "\uf18c";
        public static string FAStackExchange = "\uf18d";
        public static string FAArrowCircleORight = "\uf18e";
        public static string FAArrowCircleOLeft = "\uf190";
        public static string FACaretSquareOLeft = "\uf191";
        public static string FADotCircleO = "\uf192";
        public static string FAWheelchair = "\uf193";
        public static string FAVimeoSquare = "\uf194";
        public static string FATry = "\uf195";
        public static string FAPlusSquareO = "\uf196";
    }
}
